spring:
   application:
     name: client1

server:
   port: 1001


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
    registerWithEureka: true
    fetchRegistry: true
    instance:
       hostname: localhost


client1:
    testValue: test
