spring:
   application:
     name: main-server

server:
       port: 1000

eureka:
  client:
      registerWithEureka: false
      fetchRegistry: false
      service-url:
            defaultZone: http://localhost:1000/eureka
  server:
      waitTimeInMsWhenSyncEmpty: 0

zuul:
  routes:
    client1:
      path: /client1/**
      serviceId: client1
     # url: http://localhost:1001/
    client2:
      path: /client2/**
      serviceId: client2
     # url: http://localhost:1002/
      
